# Generated by Django 4.2 on 2023-05-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0005_blogpostmodel_owner_comment_owner_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
