# Generated by Django 4.2 on 2023-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
